### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mmghv** [mmghv/sublime-monokai-rich#2]
## TODO
- [x] 1. fix (remove) highlighting for `Blade's ignore markers` when `@` used
- [x] 2. give another look at the `comment block` backcolor, maybe make it darker
- [x] 3. add highlight for `punctuation.definition.expression` (braces of $variable inside double-quoted string)
- [x] 4. add mention to `Laravel-Blade-Highlighter` package
- [x] 5. add `Embedded Code` to the `Enhancement` list
